package io.github.olbartek.agentctl

/**
 * The host-written prose in the generated command reference: everything that is not generated from the registry.
 * [mockExample] also reaches `<cli> screens`, which lists the same runtime commands.
 */
public data class DocsText(
    val title: String,
    val intro: String,
    val usageExamples: List<String>,
    /**
     * How the generated docs spell the CLI, in the "generated by" note and the line about scenarios. Defaults to
     * [CLIName.current]; a host with a wrapper script sets that spelling (`./appctl`).
     */
    val invocation: String = CLIName.current,
    /** The command shown above [exampleStep] in the worked example. */
    val exampleCommand: String = "<command>",
    /** A single rendered step, shown as a worked example of the output. Hosts supply one from a real screen. */
    val exampleStep: String = "screen=<path> <key>=<value> … calls=<client.method>,…",
    /** How the document names the scenario files: a glob such as `scenarios/<name>.appctl` with `*` for the name. */
    val scenariosGlob: String = "scenarios/*.appctl",
    /** The example in the `mock` runtime command's help, e.g. `mock orders.fetchOrders network`. */
    val mockExample: String = AgentRegistry.DEFAULT_MOCK_EXAMPLE,
    val appendix: List<String>,
)

/** Renders `docs/agent-commands.md` from data. The output depends only on its inputs, so `docs --check` can compare it. */
public object DocsRenderer {
    public fun render(
        screens: List<ScreenDoc>,
        runtimeCommands: List<CommandDoc>,
        mockMethods: List<MockMethod>,
        text: DocsText,
    ): String {
        val out = mutableListOf<String>()
        out.add("# ${text.title}")
        out.add("")
        out.add(
            "> **GENERATED** by `${text.invocation} docs` from the screens' agent declarations. Do not edit by hand; " +
                "run `${text.invocation} docs` instead.",
        )
        out.add("")
        out.add(text.intro)
        out.add("")
        out.add("## Script syntax")
        out.add("")
        out.add("- Commands are separated by `;` or newlines. `#` starts a comment.")
        out.add("- A command's argument is the rest of the line: `<command> a value with spaces`.")
        out.add("- Double quotes protect `;` and `#`: `<command> \"a;b#c\"`. Inside quotes, `\\\"` is a quote.")
        out.add("- After each command the app settles and one step is printed:")
        out.add("")
        out.add("  ```text")
        out.add("  > ${text.exampleCommand}")
        out.add("    ${text.exampleStep}")
        out.add("  ```")
        out.add("")
        out.add("  The line holds `screen`, the screen's summary keys, `calls=` (mock calls made during the step),")
        out.add("  `error=` (if set) and `pending=` (effects waiting on the clock, e.g. a countdown; headlessly")
        out.add("  `advance <duration>` releases them).")
        out.add("- Exit codes: `0` all steps passed, `1` a command or `expect` failed, `2` usage or parse error, `3` internal error.")
        out.add("")
        out.add("## Examples")
        out.add("")
        out.add("```bash")
        out.addAll(text.usageExamples)
        out.add("```")
        out.add("")
        out.add("Scenarios in `${text.scenariosGlob}` use the same syntax plus `expect` lines; `${text.invocation} test` runs them.")
        out.add("")
        out.add("## Runtime commands (every screen)")
        out.add("")
        out.add("| Command | Description |")
        out.add("|---|---|")
        for (command in runtimeCommands) {
            out.add("| `${escape(command.usage)}` | ${escape(command.help)} |")
        }
        out.add("")
        out.add("## Screens")
        out.add("")
        for (screen in screens) {
            out.add("### `${screen.path}`")
            out.add("")
            out.add("Screen: `${screen.screen}`.")
            if (screen.summaryKeys.isNotEmpty()) {
                out.add("Summary keys: " + screen.summaryKeys.joinToString(", ") { "`$it`" } + ".")
            }
            out.add("")
            if (screen.commands.isEmpty()) {
                out.add("No screen commands; only the runtime commands apply.")
            } else {
                out.add("| Command | Description | From |")
                out.add("|---|---|---|")
                for (command in screen.commands) {
                    val note = command.note?.let { " *(${escape(it)})*" } ?: ""
                    out.add("| `${escape(command.usage)}` | ${escape(command.help)}$note | ${command.source} |")
                }
            }
            out.add("")
        }
        out.add("## Mockable methods")
        out.add("")
        out.add("`mock <method> <error>` makes the next call to the method throw that error.")
        out.add("")
        out.add("| Method | Errors |")
        out.add("|---|---|")
        for (method in mockMethods) {
            out.add("| `${method.name}` | " + method.errorCodes.joinToString(", ") { "`$it`" } + " |")
        }
        out.add("")
        out.addAll(text.appendix)
        out.add("")
        return out.joinToString("\n")
    }

    private fun escape(text: String): String = text.replace("|", "\\|")
}
